mathematics.pdf: mathematics.tex \
choices.environment.tex \
circle.solutions.tex \
circle.tex \
combinatorio.tex \
esercizi.tex \
logaritmi.tex \
moreloga.tex \
polynomials.tex \
soluzioni.tex \
trigonometria.tex
	cd images; make
	pdflatex mathematics.tex && pdflatex mathematics.tex

all:
	mathematics.pdf

clean:
	rm -f *.4ct *.4tc *.aux *.css *.dvi *.idv *.lg *.log *.ncx *.opf *.out *.tmp *.toc *.xhtml *.xref *.pdf
	cd images; make clean


mathematics.pdf: images/circles03.svg \
images/circles04.svg \
images/circ_07_00.svg \
images/circ_07.svg \
images/circ_07_01.svg \
images/circ_08_01.svg \
images/circ_08_02.svg \
images/circ_07_02.svg \
images/circ_07_03.svg \
images/circles.7.b.svg \
images/function.1.svg \
images/function.1.svg \
images/function.2.svg \
images/log12x.svg \
images/log2x.svg \
images/polynomials.1.1.svg \
images/polynomials.1.2.svg \
images/polynomials.1.3.svg \
images/polynomials.1.4.svg \
images/polynomials.1.5.svg \
images/polynomials.1.6.svg \
images/polynomials.1.7.svg \
images/polynomials.2.1.svg \
images/polynomials.2.2.svg \
images/polynomials.2.3.svg \
images/polynomials.2.4.svg \
images/polynomials.2.5.svg \
images/polynomials.2.6.svg \
images/trigo_01.svg \
images/trigo_02.svg \
images/trigo_03.svg \
images/trigo_04.svg \
images/trigo_05.svg \
images/trigo_06.svg \
images/01.svg

