all: function.1.pdf \
function.2.pdf \
log12x.pdf \
log2x.pdf \
polynomials.1.1.pdf \
polynomials.1.2.pdf \
polynomials.1.3.pdf \
polynomials.1.4.pdf \
polynomials.1.5.pdf \
polynomials.1.6.pdf \
polynomials.1.7.pdf \
polynomials.2.1.pdf \
polynomials.2.2.pdf \
polynomials.2.3.pdf \
polynomials.2.4.pdf \
polynomials.2.5.pdf \
polynomials.2.6.pdf \
trigo_01.pdf \
trigo_02.pdf \
trigo_03.pdf \
trigo_04.pdf \
trigo_05.pdf \
trigo_06.pdf \
circles_00.pdf \
circles_01.pdf \
circles_02.pdf \
circles03.pdf \
circles04.pdf \
circles.7.b.pdf \
analyzem01.pdf \
circ_06.pdf \
circ_07.pdf \
circ_07_00.pdf \
circ_07_01.pdf \
circ_08_01.pdf \
circ_08_02.pdf \
circ_07_02.pdf \
circ_07_03.pdf \
01.pdf

%.pdf: %.svg
	inkscape -o $@ $<

clean:
	rm -f *pdf
