all: function.1.pdf \
function.2.pdf \
log12x.pdf \
log2x.pdf \
polynomials.1.1.pdf \
polynomials.1.2.pdf \
polynomials.1.3.pdf \
polynomials.1.4.pdf \
polynomials.1.5.pdf \
polynomials.1.6.pdf \
polynomials.1.7.pdf \
polynomials.2.1.pdf \
polynomials.2.2.pdf \
polynomials.2.3.pdf \
polynomials.2.4.pdf \
polynomials.2.5.pdf \
polynomials.2.6.pdf \
trigo_01.pdf \
trigo_02.pdf \
trigo_03.pdf \
trigo_04.pdf \
trigo_05.pdf \
trigo_06.pdf \
analyzem01.pdf

%.pdf: %.svg
	inkscape -o $@ $<

clean:
	rm -f *pdf
