all: arrangements.pdf \
carrucole.2.pdf \
carrucole.3.pdf \
carrucole.4.pdf \
fili_01_01.pdf \
fili_01_02.pdf \
fili_01_03.pdf \
carrucole.5.pdf \
carrucole.6.pdf \
carrucole.pdf \
ex_p_1.pdf \
ex_p_2.pdf \
mot-ex-4a.pdf \
mot-ex-4b.pdf \
mot-ex-4c.pdf \
mot-ex-4d.pdf \
mot-ex-4.pdf \
moto.pdf \
rot-ex-12a.pdf \
rot-ex-12b.pdf \
rot-ex-12c.pdf \
rot-ex-12d.pdf \
rot-ex-12.pdf \
rot-ex-15.pdf \
rot-ex-1a.pdf \
rot-ex-1b.pdf \
rot-ex-1c.pdf \
rot-ex-1d.pdf \
rot-ex-1.pdf \
rot-ex-3.pdf \
rot-ex-4.pdf \
rot-ex-5.pdf \
tensione.pdf

%.pdf: %.svg
	inkscape -o $@ $<

clean:
	rm -f *pdf
